# meta-cclrte — CODESYS Control Linux RTE Yocto layer

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-cclrte"
BBFILE_PATTERN_meta-cclrte = "^${LAYERDIR}/"
# Priority 10 overrides meta-raspberrypi (7) and meta-oe (6)
BBFILE_PRIORITY_meta-cclrte = "10"

LAYERDEPENDS_meta-cclrte = "core openembedded-layer networking-layer meta-python"
LAYERSERIES_COMPAT_meta-cclrte = "scarthgap"
