"""CCLRTE Builder — web-based build and SD-card flash control server."""

from flask import (
    Flask, render_template, jsonify, request,
    Response, stream_with_context, send_file,
)
import glob
import json
import os
import re
import subprocess
import threading
import time

app = Flask(__name__, template_folder="templates")

WORKSPACE      = os.environ.get("WORKSPACE", "/workspace")
BUILD_CACHE    = os.environ.get("BUILD_CACHE_DIR", "/build-cache")

# ── Build state ────────────────────────────────────────────────────────────────
_lock        = threading.Lock()
_build_proc  = None
_log: list   = []          # All captured log lines (guarded by _lock)
_build       = {
    "status":       "idle",   # idle | running | done | error
    "target":       None,
    "progress":     0,
    "tasks_done":   0,
    "tasks_total":  0,
    "current_task": "",
    "start_time":   None,
    "elapsed":      0,
}
_flash = {
    "status":   "idle",   # idle | running | done | error
    "progress": 0,
    "message":  "",
}


# ── Helpers ────────────────────────────────────────────────────────────────────

def _set_build(**kwargs):
    with _lock:
        _build.update(kwargs)

def _log_append(line: str):
    with _lock:
        _log.append(line)

def _find_images():
    patterns = [
        f"{BUILD_CACHE}/build/tmp/deploy/images/**/*.rpi-sdimg",
        f"{WORKSPACE}/build/tmp/deploy/images/**/*.rpi-sdimg",
    ]
    seen, results = set(), []
    for pat in patterns:
        for path in sorted(glob.glob(pat, recursive=True),
                           key=os.path.getmtime, reverse=True)[:4]:
            if path not in seen and os.path.exists(path):
                seen.add(path)
                results.append({
                    "path":    path,
                    "name":    os.path.basename(path),
                    "size_mb": round(os.path.getsize(path) / 1_000_000, 1),
                    "date":    time.strftime(
                        "%Y-%m-%d %H:%M", time.localtime(os.path.getmtime(path))
                    ),
                })
    return results

def _find_codesys_packages():
    data_dir = os.path.join(WORKSPACE, "data")
    if not os.path.isdir(data_dir):
        return []
    return [
        f for f in os.listdir(data_dir)
        if f.endswith(".deb") or f.endswith(".ipk")
    ]

def _parse_bitbake_line(line: str):
    """Update progress counters from a bitbake output line."""
    m = re.search(r"Currently \d+ running tasks?\s*\((\d+) of (\d+)\)", line)
    if m:
        done, total = int(m.group(1)), int(m.group(2))
        with _lock:
            _build["tasks_done"]  = done
            _build["tasks_total"] = total
            _build["progress"]    = int(done / total * 100) if total else 0
        return

    m = re.search(r"NOTE: recipe ([\w./+-]+): task (do_\w+): Started", line)
    if m:
        _set_build(current_task=f"{m.group(1)}: {m.group(2)}")


# ── Routes ─────────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    return render_template("index.html")


@app.route("/api/status")
def api_status():
    with _lock:
        build_snap = dict(_build)
        flash_snap = dict(_flash)
        log_count  = len(_log)

    if build_snap["start_time"]:
        build_snap["elapsed"] = int(time.time() - build_snap["start_time"])

    return jsonify({
        "build":             build_snap,
        "flash":             flash_snap,
        "log_lines":         log_count,
        "images":            _find_images(),
        "codesys_packages":  _find_codesys_packages(),
    })


# ── Site configuration ─────────────────────────────────────────────────────────

@app.route("/api/site_conf", methods=["GET", "POST"])
def api_site_conf():
    conf_path   = os.path.join(WORKSPACE, "config", "site.conf")
    sample_path = os.path.join(WORKSPACE, "config", "site.conf.sample")

    if request.method == "POST":
        data = request.get_json(force=True)
        os.makedirs(os.path.dirname(conf_path), exist_ok=True)
        with open(conf_path, "w") as fh:
            fh.write("# Generated by CCLRTE Builder GUI\n")
            for key, val in data.items():
                fh.write(f'{key}="{val}"\n')
        return jsonify({"ok": True})

    # GET — read existing or fall back to sample
    cfg = {}
    for path in (conf_path, sample_path):
        if os.path.exists(path):
            with open(path) as fh:
                for raw in fh:
                    line = raw.strip()
                    if not line or line.startswith("#"):
                        continue
                    if "=" in line:
                        k, v = line.split("=", 1)
                        cfg[k.strip()] = v.strip().strip("'\"")
            break
    return jsonify(cfg)


# ── CODESYS package upload ─────────────────────────────────────────────────────

@app.route("/api/upload_package", methods=["POST"])
def api_upload_package():
    f = request.files.get("file")
    if not f:
        return jsonify({"error": "No file attached"}), 400
    if not (f.filename.endswith(".deb") or f.filename.endswith(".ipk")):
        return jsonify({"error": "Only .deb or .ipk files are accepted"}), 400

    data_dir = os.path.join(WORKSPACE, "data")
    os.makedirs(data_dir, exist_ok=True)
    dest = os.path.join(data_dir, os.path.basename(f.filename))
    f.save(dest)
    return jsonify({"ok": True, "filename": os.path.basename(dest)})


# ── Build control ──────────────────────────────────────────────────────────────

KAS_CONFIG_MAP = {
    "preempt-rt": "kas/rpi5-64.yml",
    "xenomai":    "kas/rpi5-xenomai.yml",
    "qemu":       "kas/qemu-x86-64.yml",
}


@app.route("/api/build/start", methods=["POST"])
def api_build_start():
    with _lock:
        if _build["status"] == "running":
            return jsonify({"error": "A build is already running"}), 400

    data   = request.get_json(force=True)
    target = data.get("target", "preempt-rt")
    if target not in KAS_CONFIG_MAP:
        return jsonify({"error": f"Unknown target: {target}"}), 400

    with _lock:
        _build.update({
            "status":       "running",
            "target":       target,
            "progress":     0,
            "tasks_done":   0,
            "tasks_total":  0,
            "current_task": "Initializing KAS build…",
            "start_time":   time.time(),
            "elapsed":      0,
        })
        _log.clear()

    threading.Thread(
        target=_run_build,
        args=(KAS_CONFIG_MAP[target],),
        daemon=True,
    ).start()
    return jsonify({"ok": True, "target": target})


def _run_build(kas_config: str):
    global _build_proc
    # Append the Docker overlay so repos use HTTPS and caches land on the volume
    full_config = f"{kas_config}:kas/docker.yml"
    env = {**os.environ, "PYTHONUNBUFFERED": "1"}

    try:
        _build_proc = subprocess.Popen(
            ["kas", "build", full_config],
            cwd=WORKSPACE,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
            env=env,
        )
        for line in _build_proc.stdout:
            line = line.rstrip()
            _log_append(line)
            _parse_bitbake_line(line)

        _build_proc.wait()
        rc = _build_proc.returncode
        _set_build(
            status="done" if rc == 0 else "error",
            progress=100 if rc == 0 else _build["progress"],
        )

    except Exception as exc:
        _log_append(f"[BUILD ERROR] {exc}")
        _set_build(status="error")
    finally:
        _build_proc = None


@app.route("/api/build/cancel", methods=["POST"])
def api_build_cancel():
    global _build_proc
    if _build_proc and _build_proc.poll() is None:
        _build_proc.terminate()
        _set_build(status="idle")
        return jsonify({"ok": True})
    return jsonify({"error": "No build is running"}), 400


# ── Build log streaming (Server-Sent Events) ───────────────────────────────────

@app.route("/api/build/log")
def api_build_log():
    """
    SSE endpoint.  Client sends ?since=N to skip lines it already has.
    Sends new lines as they appear, then a 'done' event when the build finishes.
    """
    since = request.args.get("since", 0, type=int)

    def generate():
        pos = since
        while True:
            with _lock:
                snapshot = _log[pos:]
                status   = _build["status"]
                total    = len(_log)

            for i, line in enumerate(snapshot):
                payload = json.dumps({"t": "l", "i": pos + i, "v": line})
                yield f"data: {payload}\n\n"
            pos += len(snapshot)

            if status not in ("running",) and pos >= total:
                yield f"data: {json.dumps({'t': 'done', 'status': status})}\n\n"
                return

            # Heartbeat keeps the connection alive; also throttles polling
            yield f"data: {json.dumps({'t': 'ping'})}\n\n"
            time.sleep(0.4)

    return Response(
        stream_with_context(generate()),
        mimetype="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


# ── SD card drive enumeration ──────────────────────────────────────────────────

@app.route("/api/drives")
def api_drives():
    try:
        r = subprocess.run(
            ["lsblk", "-J", "-o", "NAME,SIZE,TYPE,HOTPLUG,VENDOR,MODEL,TRAN"],
            capture_output=True, text=True, timeout=5,
        )
        raw = json.loads(r.stdout)
    except FileNotFoundError:
        # lsblk not available (Windows Docker Desktop without Linux tools exposed)
        return jsonify({"drives": [], "platform_note":
            "Drive detection requires a Linux host. "
            "On Windows, download the image and flash with Balena Etcher."})
    except Exception as exc:
        return jsonify({"drives": [], "error": str(exc)})

    drives = []
    for dev in raw.get("blockdevices", []):
        if dev.get("type") == "disk" and dev.get("hotplug"):
            drives.append({
                "path":   f"/dev/{dev['name']}",
                "size":   dev.get("size", "?"),
                "vendor": (dev.get("vendor") or "").strip(),
                "model":  (dev.get("model") or "").strip(),
                "tran":   dev.get("tran") or "usb",
            })
    return jsonify({"drives": drives})


# ── SD card flash ──────────────────────────────────────────────────────────────

# Devices we refuse to overwrite even when the user asks
_SYSTEM_DISKS = {"/dev/sda", "/dev/vda", "/dev/nvme0n1", "/dev/mmcblk0"}


@app.route("/api/flash/start", methods=["POST"])
def api_flash_start():
    with _lock:
        if _flash["status"] == "running":
            return jsonify({"error": "A flash operation is already running"}), 400

    data   = request.get_json(force=True)
    device = data.get("device", "").strip()
    image  = data.get("image", "").strip()

    if not device.startswith("/dev/"):
        return jsonify({"error": "Invalid device path"}), 400
    if device in _SYSTEM_DISKS:
        return jsonify({"error": f"Refusing to flash system disk {device}"}), 400
    if not image or not os.path.exists(image):
        return jsonify({"error": "Image file not found on server"}), 404

    with _lock:
        _flash.update({"status": "running", "progress": 0, "message": "Starting…"})

    threading.Thread(target=_run_flash, args=(device, image), daemon=True).start()
    return jsonify({"ok": True})


def _run_flash(device: str, image: str):
    size = os.path.getsize(image)
    try:
        # Unmount any auto-mounted partitions
        for suffix in ("1", "2", "p1", "p2"):
            subprocess.run(
                ["sudo", "umount", "-f", f"{device}{suffix}"],
                capture_output=True,
            )

        proc = subprocess.Popen(
            ["sudo", "dd", f"if={image}", f"of={device}",
             "bs=4M", "conv=fsync", "status=progress"],
            stderr=subprocess.PIPE, text=True,
        )
        for line in proc.stderr:
            m = re.search(r"(\d+) bytes", line)
            if m:
                pct = min(99, int(int(m.group(1)) / size * 100))
                with _lock:
                    _flash.update({"progress": pct, "message": line.strip()})

        proc.wait()
        with _lock:
            if proc.returncode == 0:
                _flash.update({"status": "done", "progress": 100,
                               "message": "Flash complete! Safely remove the SD card."})
                # Copy site.conf to boot partition if it exists
                _copy_site_conf(device)
            else:
                _flash.update({"status": "error", "progress": 0,
                               "message": "dd failed — check that the device is writable."})

    except Exception as exc:
        with _lock:
            _flash.update({"status": "error", "progress": 0, "message": str(exc)})


def _copy_site_conf(device: str):
    """Mount the FAT boot partition and copy site.conf into it."""
    site_conf = os.path.join(WORKSPACE, "config", "site.conf")
    if not os.path.exists(site_conf):
        return

    boot_part = f"{device}p1" if re.search(r"mmcblk|nvme", device) else f"{device}1"
    mnt = f"/tmp/cclrte_boot_{os.getpid()}"
    try:
        os.makedirs(mnt, exist_ok=True)
        r = subprocess.run(["sudo", "mount", boot_part, mnt], capture_output=True)
        if r.returncode == 0:
            subprocess.run(["sudo", "cp", site_conf, f"{mnt}/site.conf"])
            subprocess.run(["sudo", "umount", mnt])
            with _lock:
                _flash["message"] += " site.conf copied to /boot."
    except Exception:
        pass
    finally:
        subprocess.run(["sudo", "rmdir", mnt], capture_output=True)


# ── Image download ─────────────────────────────────────────────────────────────

@app.route("/api/download_image")
def api_download_image():
    path = request.args.get("path", "")
    # Only serve files that live inside the known output directories
    allowed = (
        path.startswith(f"{BUILD_CACHE}/build/tmp/deploy/") or
        path.startswith(f"{WORKSPACE}/build/tmp/deploy/")
    )
    if not allowed or not os.path.isfile(path):
        return jsonify({"error": "File not found or path not allowed"}), 404
    return send_file(path, as_attachment=True,
                     download_name=os.path.basename(path))


# ── Entry point ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("  CCLRTE Builder  →  http://localhost:5000")
    print("=" * 60)
    app.run(host="0.0.0.0", port=5000, threaded=True, debug=False)
